options:
  docker: true

definitions:
  steps:
    - step: &build-hl-create-acct-image
        name: Build HL Create Acct Docker image
        image: adoptopenjdk/openjdk11:jre-11.0.9_11.1-alpine
        script:
          - apk add --no-cache openssh-client bash
          - cp .env.example .env
          - docker build -f deployment/Dockerfile -t hl-create-acct  .
          - docker save --output tmp-image.docker hl-create-acct
        artifacts:
          - tmp-image.docker

    - step: &docker-push-and-deploy-cloudrun
        name: Build - Push - Deploy to GCP for HL Create Acct
        image: google/cloud-sdk:latest
        caches:
          - docker
        deployment: test
        script:
          - docker load --input ./tmp-image.docker
          - export SERVICE_NAME='hl-create-acct'
          - export PROJECT_NAME='extreme-arch-347212'
          - echo $GCLOUD_API_KEYFILE | base64 -d > ./gcloud-api-key.json
          - gcloud auth activate-service-account --key-file gcloud-api-key.json
          - gcloud config list
          - gcloud config set project $PROJECT_NAME
          - export IMAGE_NAME=us-central1-docker.pkg.dev/extreme-arch-347212/hl-create-acct/hl-create-acct:$(echo $BITBUCKET_COMMIT | cut -c1-8)
          - docker tag hl-create-acct ${IMAGE_NAME}
          # check if google artifacts repository exist. If not create
          - gcloud artifacts repositories list|grep hl-create-acct || gcloud artifacts repositories create hl-create-acct --repository-format=docker --location=us-central1
          # Login to google artifact registry
          - gcloud auth configure-docker us-central1-docker.pkg.dev
          - docker push ${IMAGE_NAME}
          - docker push $IMAGE_NAME
          - gcloud run deploy $SERVICE_NAME --image $IMAGE_NAME --region us-central1 --project $PROJECT_NAME --platform managed --allow-unauthenticated

          - echo "ALL DONE DEPLOYMENT HAS BEEN SUCCEDED"

pipelines:
  tags:
    v*:
      - step: *build-hl-create-acct-image

  default:
    - step: *build-hl-create-acct-image
    - step: *docker-push-and-deploy-cloudrun
